apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.host }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: redis 
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.users.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
      - name: users-service
        image: "{{ .Values.registry }}/sae503-users:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host | quote }}
          - name: ADMIN_KEY
            value: {{ .Values.adminKey | default "default_key" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.users.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: users-pod
  ports:
  - port: {{ .Values.services.users.port }}
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.search.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: search-pod
  template:
    metadata:
      labels:
        app: search-pod
    spec:
      containers:
      - name: search-service
        image: "{{ .Values.registry }}/sae503-search:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host | quote }}
          - name: ADMIN_KEY
            value: {{ .Values.adminKey | default "default_key" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.search.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: search-pod
  ports:
  - port: {{ .Values.services.search.port }}
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.quotes.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quotes-pod
  template:
    metadata:
      labels:
        app: quotes-pod
    spec:
      containers:
      - name: quotes-service
        image: "{{ .Values.registry }}/sae503-quotes:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host | quote }}
          - name: ADMIN_KEY
            value: {{ .Values.adminKey | default "default_key" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.quotes.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: quotes-pod
  ports:
  - port: {{ .Values.services.quotes.port }}
    targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.users.serviceName }}
            port:
              number: {{ .Values.ingress.externalPort }}
      - path: /quotes
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.quotes.serviceName }}
            port:
              number: {{ .Values.ingress.externalPort }}
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.search.serviceName }}
            port:
              number: {{ .Values.ingress.externalPort }}