services:
  users:
    image: kitami1/sae503-users:1.0.0
    ports:
      - "80:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - APP_PORT=5000
      - ADMIN_KEY=default_key
      - CSV_FILE_USERS=/citations_haddock/data/initial_data_users.csv
      - CSV_FILE_QUOTES=/citations_haddock/data/initial_data_quotes.csv
  quotes:
    image: kitami1/sae503-quotes:1.0.0
    ports:
      - "80:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - APP_PORT=5000
      - ADMIN_KEY=default_key
      - CSV_FILE_USERS=/citations_haddock/data/initial_data_users.csv
      - CSV_FILE_QUOTES=/citations_haddock/data/initial_data_quotes.csv
  search:
    image: kitami1/sae503-search:1.0.0
    ports:
      - "80:5002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - APP_PORT=5000
      - ADMIN_KEY=default_key
      - CSV_FILE_USERS=/citations_haddock/data/initial_data_users.csv
      - CSV_FILE_QUOTES=/citations_haddock/data/initial_data_quotes.csv

  redis:
    image: redis:8
    ports:
      - "6379:6379"
