# kustomization.yaml
# Configuration Kustomize principale pour le projet

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Liste des ressources à déployer
resources:
- traefik/ # Déploiement Traefik
- whoami.yaml
- whoami-service.yaml
- whoami-ingress.yaml

# Configuration commune pour toutes les ressources
labels:
- pairs:
    app.kubernetes.io/part-of: sae503-kc-md

# Namespace par défaut
namespace: haddock

# Configuration pour les images (si besoin de personnalisation)
# images:
#   - name: traefik
#     newName: traefik
#     newTag: v2.11
#   - name: containous/whoami
#     newName: containous/whoami
#     newTag: v1.8
